### ISSUE TITLE
Observation.valueQuantity nicht validierbar

### ISSUE THREAD

**Issue by alexzautke** [acnb/MII-Laboratory#8]
[David Meyers](https://simplifier.net/user/davidmeyers) commented 2 months ago
Hallo,
ist das ein Problem unseres (HAPI-)Validierers oder ein Problem in der Profilierung?
"valueQuantity": {
                    "value": 0.0,
                    "unit": "BE/ml",
                    "system": "http://unitsofmeasure.org",
                    "code": "[arb'U]/mL"
                }
führt zu:
{
                        "severity": "error",
                        "code": "processing",
                        "details": {
                            "coding": [
                                {
                                    "system": "http://hl7.org/fhir/java-core-messageId",
                                    "code": "Extension_PROF_Type"
                                }
                            ]
                        },
                        "diagnostics": "The Profile 'https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab|1.0' definition allows for the type CodeableConcept but found type Quantity",
                        "location": [
                            "Bundle.entry[0].resource.ofType(Observation).value.ofType(Quantity)",
                            "Line 1, Col 1457"
                        ]
                    }
Laut Profil sollten sowohl valueQuantity, als auch valueCodeableConcept ok sein.

**Comment by dmeyers138** [comment]
Hallo,

gibt es hier zu schon eine Erkenntnis oder sogar einen Hotfix? 
Die Meldung kommt 1:n mal pro Ressource vor, nämlich für jedes Attribut des Quantity-Objekts und dementsprechend umfangreich sind die Validator-Nachrichten.
Aktuell sind bei einer 92k Zeilen Response für Observations + Validierungsmeldungen knapp 60.000 Zeilen nur vom Validerer... 
Das macht das Finden "wirklicher" Errors etwas schwierig.

Danke!
